// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelcellTickets.Api.Data;

#nullable disable

namespace TelcellTickets.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701090000_AddSeatingPlan")]
    partial class AddSeatingPlan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            SeatingPlanModelSnapshot.Build(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
